### ISSUE TITLE
Release latest version so sensu can gem install it

### ISSUE THREAD

**Issue by raffraffraff** [sensu/sensu-extensions-occurrences#11]
The latest _release_ of this extension is 1.2.0, and it doesn't contain the latest _merge_. I'm waiting for the version from 8 months ago. Can you please do a new release of this extension so Sensu can gem install the latest version?

**Comment by majormoses** [comment]
I made a release but was unable to actually push it to rubygems.org:
```
You do not have permission to push to this gem. Ask an owner to add you with: gem owner sensu-extensions-occurrences --add me@benabrams.it
```

@portertech I need you grant me access

**Comment by majormoses** [comment]
@portertech makes sense, please ping me on the PR so I can know the process and make the PR into core after releasing versions of core extensions in the future.

> Core pins all direct dependency versions, for install and loading.

You know I am all for that...

**Comment by cwjohnston** [comment]
1.3.0 was released on Mar 26, 2018 (h/t to majormoses), but as noted above can't be activated in packaged versions of Sensu Core. 

As a result, I'm closing this issue in favor of https://github.com/sensu/sensu-extensions/issues/22 which should help us get this into a future Core release
