### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by runningman84** [sensu/sensu-extensions-occurrences#3]
Please document hwo to use the occurces filter.
https://sensuapp.org/docs/0.26/reference/extensions.html

I used to have a config like this

```
sensu_filter 'occurrences' do
  attributes(occurrences: 'eval: value > :::check.occurrences|10:::')
end
```

How does the extension work? Is it possible to define a default occurrences setting (like above) if nothing is set?

**Comment by amdprophet** [comment]
Hey @runningman84,

It looks like default occurrences isn't supported in this filter extension. Is this something you're still hoping to see in a future release?

**Comment by runningman84** [comment]
yes a  default value which can be configured somewhere makes sense from my point of view...

**Comment by cwjohnston** [comment]
Closing as this filter is now documented https://docs.sensu.io/sensu-core/latest/reference/filters/#built-in-filters-occurrences
