### ISSUE TITLE
Can't use interpolation tokens for occurrences or refresh

### ISSUE THREAD

**Issue by raffraffraff** [sensu/sensu-extensions-occurrences#7]
## Expected Behavior
When I use interpolation tokens for 'occurrences' and 'refresh', the are looked up and the values are converted integers. If the lookup fails, or the conversion to integer fails, then the defaults will be used.

## Current Behavior
In order to use interpolation tokens, it is necessary to wrap them in quotes, or Sensu Client chokes on the "additional colons" in the `:::check.token:::`. However, when the token is wrapped in double quotes, the occurrences extension treats the quoted token values as strings, and does not attempt to convert them. This results in 'default' values being silently used.

## Steps to reproduce
Create a check definition JSON file that uses interpolation tokens for 'occurrences' and 'refresh'. Example:
```
{
  "checks": {
    "check_test": {
      "low_flap_threshold": 10,
      "interval": 60,
      "subscribers": [ "test-subscription ],
      "command": "/bin/false",
      "high_flap_threshold": 25,
      "standalone": false,
      "occurrences": ":::check_test.occurrences|5:::",
      "refresh": ":::check_test.refresh|1800:::"
    }
  }
}
```

## Context
We are a Puppet/Hiera/Sensu house, and we wish to use standard hiera patterns to deploy 'global' published checks, and use per-client client_custom data to override the interpolation tokens' default values. This works great for check parameters, but it does not work for 'refresh' or 'occurrences', which must be overridden via overrides to the puppet ::sensu::check parameters. Not the end of the world, but it means that our engineers must define overrides in two places.

## My Environment
Sensu version used: 0.28.x
Operating System: Host: CentOS 6 / CentOS 7

## Possible Solution
I have [forked the code](https://github.com/raffraffraff/sensu-extensions-occurrences) and added a str2int function that returns integers unchanged, tries to convert strings to integers, or returns nil on failure. I modified the occurrences and refresh variables to use the function. This is a hack but it works.

**Comment by raffraffraff** [comment]
I am running the fork in our test environment. I don't want to have our engineers all jump onto this bandwagon and use client custom overrides if it turns out that Sensu will never take this path (i.e. using interpolation tokens for refresh / occurrences overrides).

**Comment by cwjohnston** [comment]
@raffraffraff thanks for raising this issue. I think this makes sense, but I am curious to see if a similar change elsewhere in Sensu Core would make this less of a special feature specific to this extension.

@portertech thoughts on this? see comparison for what I assume would be in the PR here: https://github.com/sensu-extensions/sensu-extensions-occurrences/compare/master...raffraffraff:master

**Comment by raffraffraff** [comment]
@cwjohnston I though about making the change elsewhere. but I couldn't find anywhere that made more sense.  sensu/lib/sensu/utilities.rb has the two functions that perform substitution
* function substitute_tokens (tokens=string, attributes=hash), which returns an array containing a string of substituted tokens.
* function object_substitute_tokens(object, attributes=hash), returns array containing updated object
..but neither of these functions care which attribute that the token is assigned to. Since the values 'occurrences' and 'refresh' do not apply to the check, the extension is the only place I could think of doing it. But I didn't delve further into the code to find other places to put it.
